name: weather_app
description: "my first weather app through this I am learning Flutter and app development"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # Add only once
  cupertino_icons: ^1.0.8  # Add only once
  intl: ^0.18.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/weather.jpeg
    - lib/assets/cloud.jpeg